### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by Baayeh** [Baayeh/second-capstone#21]
https://github.com/users/Baayeh/projects/1

- We are two in the group
   1. @Daphineatim 
   2.  @Baayeh

**Comment by dasileker** [comment]
### **Hi @Baayeh,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- Hello and good job on adding kanban cards, but you didn't attribute the cards between the two of you we should see the student tag instead of `Student A or B`, also you are missing two other cards you should have 15 card not 13.

## Optional `suggestions`
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Baayeh** [comment]
The required changes have been implemented.
- The various cards have been assigned
